sudo: false
language: android
jdk:
  - oraclejdk8

android:
    components:
      - build-tools-22.0.1
      - android-22
      - extra

before_script:
  - chmod +x gradlew

script:
    - ./gradlew check --info

